// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: cards.sql

package cardsQuery

import (
	"context"
)

const getCard = `-- name: GetCard :one
SELECT 
    c.uuid,
    c.name,
    c.setCode,
    c.manaValue,
    c.rarity,
    c.colors,
    c.types,
    s.name AS setName
FROM 
    cardIdentifiers ci
JOIN 
    cards c ON ci.uuid = c.uuid
JOIN 
    sets s ON c.setCode = s.code
WHERE 
    ci.scryfallId = ?
`

type GetCardRow struct {
	Uuid      string  `json:"uuid"`
	Name      string  `json:"name"`
	Setcode   string  `json:"setcode"`
	Manavalue float64 `json:"manavalue"`
	Rarity    string  `json:"rarity"`
	Colors    string  `json:"colors"`
	Types     string  `json:"types"`
	Setname   string  `json:"setname"`
}

func (q *Queries) GetCard(ctx context.Context, scryfallid string) (GetCardRow, error) {
	row := q.queryRow(ctx, q.getCardStmt, getCard, scryfallid)
	var i GetCardRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Setcode,
		&i.Manavalue,
		&i.Rarity,
		&i.Colors,
		&i.Types,
		&i.Setname,
	)
	return i, err
}
