// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package cardsQuery

import (
	"database/sql"
)

type Card struct {
	Artist                  sql.NullString  `json:"artist"`
	Artistids               sql.NullString  `json:"artistids"`
	Asciiname               sql.NullString  `json:"asciiname"`
	Attractionlights        sql.NullString  `json:"attractionlights"`
	Availability            sql.NullString  `json:"availability"`
	Boostertypes            sql.NullString  `json:"boostertypes"`
	Bordercolor             sql.NullString  `json:"bordercolor"`
	Cardparts               sql.NullString  `json:"cardparts"`
	Coloridentity           sql.NullString  `json:"coloridentity"`
	Colorindicator          sql.NullString  `json:"colorindicator"`
	Colors                  string          `json:"colors"`
	Defense                 sql.NullString  `json:"defense"`
	Dueldeck                sql.NullString  `json:"dueldeck"`
	Edhrecrank              sql.NullInt64   `json:"edhrecrank"`
	Edhrecsaltiness         sql.NullFloat64 `json:"edhrecsaltiness"`
	Faceconvertedmanacost   sql.NullFloat64 `json:"faceconvertedmanacost"`
	Faceflavorname          sql.NullString  `json:"faceflavorname"`
	Facemanavalue           sql.NullFloat64 `json:"facemanavalue"`
	Facename                sql.NullString  `json:"facename"`
	Finishes                sql.NullString  `json:"finishes"`
	Flavorname              sql.NullString  `json:"flavorname"`
	Flavortext              sql.NullString  `json:"flavortext"`
	Frameeffects            sql.NullString  `json:"frameeffects"`
	Frameversion            sql.NullString  `json:"frameversion"`
	Hand                    sql.NullString  `json:"hand"`
	Hasalternativedecklimit sql.NullBool    `json:"hasalternativedecklimit"`
	Hascontentwarning       sql.NullBool    `json:"hascontentwarning"`
	Hasfoil                 sql.NullBool    `json:"hasfoil"`
	Hasnonfoil              sql.NullBool    `json:"hasnonfoil"`
	Isalternative           sql.NullBool    `json:"isalternative"`
	Isfullart               sql.NullBool    `json:"isfullart"`
	Isfunny                 sql.NullBool    `json:"isfunny"`
	Isgamechanger           sql.NullBool    `json:"isgamechanger"`
	Isonlineonly            sql.NullBool    `json:"isonlineonly"`
	Isoversized             sql.NullBool    `json:"isoversized"`
	Ispromo                 sql.NullBool    `json:"ispromo"`
	Isrebalanced            sql.NullBool    `json:"isrebalanced"`
	Isreprint               sql.NullBool    `json:"isreprint"`
	Isreserved              sql.NullBool    `json:"isreserved"`
	Isstarter               sql.NullBool    `json:"isstarter"`
	Isstoryspotlight        sql.NullBool    `json:"isstoryspotlight"`
	Istextless              sql.NullBool    `json:"istextless"`
	Istimeshifted           sql.NullBool    `json:"istimeshifted"`
	Keywords                sql.NullString  `json:"keywords"`
	Language                sql.NullString  `json:"language"`
	Layout                  sql.NullString  `json:"layout"`
	Leadershipskills        sql.NullString  `json:"leadershipskills"`
	Life                    sql.NullString  `json:"life"`
	Loyalty                 sql.NullString  `json:"loyalty"`
	Manacost                sql.NullString  `json:"manacost"`
	Manavalue               float64         `json:"manavalue"`
	Name                    string          `json:"name"`
	Number                  sql.NullString  `json:"number"`
	Originalprintings       sql.NullString  `json:"originalprintings"`
	Originalreleasedate     sql.NullString  `json:"originalreleasedate"`
	Originaltext            sql.NullString  `json:"originaltext"`
	Originaltype            sql.NullString  `json:"originaltype"`
	Otherfaceids            sql.NullString  `json:"otherfaceids"`
	Power                   sql.NullString  `json:"power"`
	Printings               sql.NullString  `json:"printings"`
	Promotypes              sql.NullString  `json:"promotypes"`
	Rarity                  string          `json:"rarity"`
	Rebalancedprintings     sql.NullString  `json:"rebalancedprintings"`
	Relatedcards            sql.NullString  `json:"relatedcards"`
	Securitystamp           sql.NullString  `json:"securitystamp"`
	Setcode                 string          `json:"setcode"`
	Side                    sql.NullString  `json:"side"`
	Signature               sql.NullString  `json:"signature"`
	Sourceproducts          sql.NullString  `json:"sourceproducts"`
	Subsets                 sql.NullString  `json:"subsets"`
	Subtypes                sql.NullString  `json:"subtypes"`
	Supertypes              sql.NullString  `json:"supertypes"`
	Text                    sql.NullString  `json:"text"`
	Toughness               sql.NullString  `json:"toughness"`
	Type                    sql.NullString  `json:"type"`
	Types                   string          `json:"types"`
	Uuid                    string          `json:"uuid"`
	Variations              sql.NullString  `json:"variations"`
	Watermark               sql.NullString  `json:"watermark"`
}

type Cardidentifier struct {
	Cardkingdometchedid      sql.NullString `json:"cardkingdometchedid"`
	Cardkingdomfoilid        sql.NullString `json:"cardkingdomfoilid"`
	Cardkingdomid            sql.NullString `json:"cardkingdomid"`
	Cardspherefoilid         sql.NullString `json:"cardspherefoilid"`
	Cardsphereid             sql.NullString `json:"cardsphereid"`
	Deckboxid                sql.NullString `json:"deckboxid"`
	Mcmid                    sql.NullString `json:"mcmid"`
	Mcmmetaid                sql.NullString `json:"mcmmetaid"`
	Mtgarenaid               sql.NullString `json:"mtgarenaid"`
	Mtgjsonfoilversionid     sql.NullString `json:"mtgjsonfoilversionid"`
	Mtgjsonnonfoilversionid  sql.NullString `json:"mtgjsonnonfoilversionid"`
	Mtgjsonv4id              sql.NullString `json:"mtgjsonv4id"`
	Mtgofoilid               sql.NullString `json:"mtgofoilid"`
	Mtgoid                   sql.NullString `json:"mtgoid"`
	Multiverseid             sql.NullString `json:"multiverseid"`
	Scryfallcardbackid       sql.NullString `json:"scryfallcardbackid"`
	Scryfallid               string         `json:"scryfallid"`
	Scryfallillustrationid   sql.NullString `json:"scryfallillustrationid"`
	Scryfalloracleid         sql.NullString `json:"scryfalloracleid"`
	Tcgplayeretchedproductid sql.NullString `json:"tcgplayeretchedproductid"`
	Tcgplayerproductid       sql.NullString `json:"tcgplayerproductid"`
	Uuid                     sql.NullString `json:"uuid"`
}

type CardsPrice struct {
	CardID    string  `json:"card_id"`
	Finish    string  `json:"finish"`
	Type      string  `json:"type"`
	Price     float64 `json:"price"`
	UpdatedAt string  `json:"updated_at"`
}

type CardsVendor struct {
	CardID    string `json:"card_id"`
	VendorID  string `json:"vendor_id"`
	Qty       int64  `json:"qty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Set struct {
	Basesetsize      sql.NullInt64  `json:"basesetsize"`
	Block            sql.NullString `json:"block"`
	Cardspheresetid  sql.NullInt64  `json:"cardspheresetid"`
	Code             string         `json:"code"`
	Isfoilonly       sql.NullBool   `json:"isfoilonly"`
	Isforeignonly    sql.NullBool   `json:"isforeignonly"`
	Isnonfoilonly    sql.NullBool   `json:"isnonfoilonly"`
	Isonlineonly     sql.NullBool   `json:"isonlineonly"`
	Ispartialpreview sql.NullBool   `json:"ispartialpreview"`
	Keyrunecode      sql.NullString `json:"keyrunecode"`
	Languages        sql.NullString `json:"languages"`
	Mcmid            sql.NullInt64  `json:"mcmid"`
	Mcmidextras      sql.NullInt64  `json:"mcmidextras"`
	Mcmname          sql.NullString `json:"mcmname"`
	Mtgocode         sql.NullString `json:"mtgocode"`
	Name             string         `json:"name"`
	Parentcode       sql.NullString `json:"parentcode"`
	Releasedate      sql.NullString `json:"releasedate"`
	Tcgplayergroupid sql.NullInt64  `json:"tcgplayergroupid"`
	Tokensetcode     sql.NullString `json:"tokensetcode"`
	Totalsetsize     sql.NullInt64  `json:"totalsetsize"`
	Type             sql.NullString `json:"type"`
}
