// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package appDB

import (
	"database/sql"
)

type Card struct {
	ID         string         `json:"id"`
	NameEn     string         `json:"name_en"`
	NameEs     string         `json:"name_es"`
	Sku        string         `json:"sku"`
	SetName    string         `json:"set_name"`
	SetCode    string         `json:"set_code"`
	ManaValue  int64          `json:"mana_value"`
	Colors     string         `json:"colors"`
	Types      string         `json:"types"`
	Rarity     string         `json:"rarity"`
	Number     string         `json:"number"`
	Finish     string         `json:"finish"`
	HasVendor  bool           `json:"has_vendor"`
	Language   string         `json:"language"`
	Visibility int64          `json:"visibility"`
	ImagePath  sql.NullString `json:"image_path"`
	ImageUrl   string         `json:"image_url"`
	Stock      int64          `json:"stock"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type CardsPrice struct {
	CardID    string  `json:"card_id"`
	Finish    string  `json:"finish"`
	Type      string  `json:"type"`
	Price     float64 `json:"price"`
	UpdatedAt string  `json:"updated_at"`
}

type CardsVendor struct {
	CardID    string `json:"card_id"`
	VendorID  string `json:"vendor_id"`
	Qty       int64  `json:"qty"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
