// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mtgDB

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getCardStmt, err = db.PrepareContext(ctx, getCard); err != nil {
		return nil, fmt.Errorf("error preparing query GetCard: %w", err)
	}
	if q.getCardIdStmt, err = db.PrepareContext(ctx, getCardId); err != nil {
		return nil, fmt.Errorf("error preparing query GetCardId: %w", err)
	}
	if q.getCardNameESStmt, err = db.PrepareContext(ctx, getCardNameES); err != nil {
		return nil, fmt.Errorf("error preparing query GetCardNameES: %w", err)
	}
	if q.getSetNameStmt, err = db.PrepareContext(ctx, getSetName); err != nil {
		return nil, fmt.Errorf("error preparing query GetSetName: %w", err)
	}
	if q.getSetsStmt, err = db.PrepareContext(ctx, getSets); err != nil {
		return nil, fmt.Errorf("error preparing query GetSets: %w", err)
	}
	if q.listAllNamesStmt, err = db.PrepareContext(ctx, listAllNames); err != nil {
		return nil, fmt.Errorf("error preparing query ListAllNames: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getCardStmt != nil {
		if cerr := q.getCardStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCardStmt: %w", cerr)
		}
	}
	if q.getCardIdStmt != nil {
		if cerr := q.getCardIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCardIdStmt: %w", cerr)
		}
	}
	if q.getCardNameESStmt != nil {
		if cerr := q.getCardNameESStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCardNameESStmt: %w", cerr)
		}
	}
	if q.getSetNameStmt != nil {
		if cerr := q.getSetNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSetNameStmt: %w", cerr)
		}
	}
	if q.getSetsStmt != nil {
		if cerr := q.getSetsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSetsStmt: %w", cerr)
		}
	}
	if q.listAllNamesStmt != nil {
		if cerr := q.listAllNamesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAllNamesStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                DBTX
	tx                *sql.Tx
	getCardStmt       *sql.Stmt
	getCardIdStmt     *sql.Stmt
	getCardNameESStmt *sql.Stmt
	getSetNameStmt    *sql.Stmt
	getSetsStmt       *sql.Stmt
	listAllNamesStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                tx,
		tx:                tx,
		getCardStmt:       q.getCardStmt,
		getCardIdStmt:     q.getCardIdStmt,
		getCardNameESStmt: q.getCardNameESStmt,
		getSetNameStmt:    q.getSetNameStmt,
		getSetsStmt:       q.getSetsStmt,
		listAllNamesStmt:  q.listAllNamesStmt,
	}
}
