CREATE TABLE cards (
	artist TEXT,
	artistIds TEXT,
	asciiName TEXT,
	attractionLights TEXT,
	availability TEXT,
	boosterTypes TEXT,
	borderColor TEXT,
	cardParts TEXT,
	colorIdentity TEXT,
	colorIndicator TEXT,
	colors TEXT NOT NULL,
	defense TEXT,
	duelDeck TEXT,
	edhrecRank INTEGER,
	edhrecSaltiness FLOAT,
	faceConvertedManaCost FLOAT,
	faceFlavorName TEXT,
	faceManaValue FLOAT,
	faceName TEXT,
	finishes TEXT,
	flavorName TEXT,
	flavorText TEXT,
	frameEffects TEXT,
	frameVersion TEXT,
	hand TEXT,
	hasAlternativeDeckLimit BOOLEAN,
	hasContentWarning BOOLEAN,
	hasFoil BOOLEAN,
	hasNonFoil BOOLEAN,
	isAlternative BOOLEAN,
	isFullArt BOOLEAN,
	isFunny BOOLEAN,
	isGameChanger BOOLEAN,
	isOnlineOnly BOOLEAN,
	isOversized BOOLEAN,
	isPromo BOOLEAN,
	isRebalanced BOOLEAN,
	isReprint BOOLEAN,
	isReserved BOOLEAN,
	isStarter BOOLEAN,
	isStorySpotlight BOOLEAN,
	isTextless BOOLEAN,
	isTimeshifted BOOLEAN,
	keywords TEXT,
	language TEXT,
	layout TEXT,
	leadershipSkills TEXT,
	life TEXT,
	loyalty TEXT,
	manaCost TEXT,
	manaValue FLOAT NOT NULL,
	name TEXT NOT NULL,
	number TEXT,
	originalPrintings TEXT,
	originalReleaseDate TEXT,
	originalText TEXT,
	originalType TEXT,
	otherFaceIds TEXT,
	power TEXT,
	printings TEXT,
	promoTypes TEXT,
	rarity TEXT NOT NULL,
	rebalancedPrintings TEXT,
	relatedCards TEXT,
	securityStamp TEXT,
	setCode TEXT NOT NULL,
	side TEXT,
	signature TEXT,
	sourceProducts TEXT,
	subsets TEXT,
	subtypes TEXT,
	supertypes TEXT,
	text TEXT,
	toughness TEXT,
	type TEXT,
	types TEXT NOT NULL,
	uuid VARCHAR(36) NOT NULL,
	variations TEXT,
	watermark TEXT
)


CREATE TABLE cardIdentifiers (
	cardKingdomEtchedId TEXT,
	cardKingdomFoilId TEXT,
	cardKingdomId TEXT,
	cardsphereFoilId TEXT,
	cardsphereId TEXT,
	deckboxId TEXT,
	mcmId TEXT,
	mcmMetaId TEXT,
	mtgArenaId TEXT,
	mtgjsonFoilVersionId TEXT,
	mtgjsonNonFoilVersionId TEXT,
	mtgjsonV4Id TEXT,
	mtgoFoilId TEXT,
	mtgoId TEXT,
	multiverseId TEXT,
	scryfallCardBackId TEXT,
	scryfallId TEXT NOT NULL,
	scryfallIllustrationId TEXT,
	scryfallOracleId TEXT,
	tcgplayerEtchedProductId TEXT,
	tcgplayerProductId TEXT,
	uuid TEXT
)

CREATE TABLE sets (
	baseSetSize INTEGER,
	block TEXT,
	cardsphereSetId INTEGER,
	code VARCHAR(8) UNIQUE NOT NULL,
	isFoilOnly BOOLEAN,
	isForeignOnly BOOLEAN,
	isNonFoilOnly BOOLEAN,
	isOnlineOnly BOOLEAN,
	isPartialPreview BOOLEAN,
	keyruneCode TEXT,
	languages TEXT,
	mcmId INTEGER,
	mcmIdExtras INTEGER,
	mcmName TEXT,
	mtgoCode TEXT,
	name TEXT NOT NULL,
	parentCode TEXT,
	releaseDate TEXT,
	tcgplayerGroupId INTEGER,
	tokenSetCode TEXT,
	totalSetSize INTEGER,
	type TEXT
)